# Development Environment Database Configuration
# This file contains database connection settings for local development
# Encrypt with: sops -e -i secrets/development/database.yaml

database:
  primary:
    host: "localhost"
    port: 5432
    name: "menschlichkeit_dev"
    username: "dev_user"
    password: "dev_password_123"
    ssl_mode: "disable"
    
  test:
    host: "localhost"
    port: 5432
    name: "menschlichkeit_test"
    username: "test_user"
    password: "test_password_123"
    ssl_mode: "disable"

redis:
  host: "localhost"
  port: 6379
  password: ""
  database: 0

# Local development API keys (non-sensitive)
api_keys:
  stripe_test_key: "pk_test_51234567890abcdef"
  google_analytics: "G-DEV123456789"
  
# SMTP Settings for local testing
smtp:
  host: "localhost"
  port: 1025  # MailHog or similar
  username: ""
  password: ""
  encryption: "none"