exclude: |
  ^vendor/|
  ^node_modules/|
  ^dist/|
  ^build/|
  ^coverage/|
  ^playwright-results/|
  ^frontend/dist/|
  ^website/dist/|
  ^web/games/assets/generated/|
  ^generated/
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
        exclude: |
          ^crm\.menschlichkeit-oesterreich\.at/web/core/tests/|
          ^crm\.menschlichkeit-oesterreich\.at/web/core/modules/.*/tests/|
          ^crm\.menschlichkeit-oesterreich\.at/web/core/themes/.*/tests/
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.18.0
    hooks:
      - id: gitleaks
        args: ["protect", "--staged", "--redact", "--config=.gitleaks.toml"]
