# Pre-commit hooks configuration
# Install with: pip install pre-commit && pre-commit install
# Run manually: pre-commit run --all-files

repos:
  # Security scanning
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        args: ['-ll', '-i', '--recursive', 'scripts/', 'enterprise-upgrade/scripts/']
        exclude: ^(node_modules/|vendor/|web/core/)
        stages: [commit]

  # Secret detection
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.2
    hooks:
      - id: gitleaks
        stages: [commit]

  # Python code quality
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3.12
        exclude: ^(node_modules/|vendor/|web/core/)

  # Python linting
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        args: ['--max-line-length=100', '--ignore=E203,W503']
        exclude: ^(node_modules/|vendor/|web/core/)

  # File checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: ^(.*\.md|.*\.txt)$
      - id: end-of-file-fixer
        exclude: ^(.*\.md|.*\.txt)$
      - id: check-yaml
        exclude: ^(.github/workflows/)
      - id: check-json
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: detect-private-key
        exclude: ^(secrets/|.*\.example)
      - id: check-merge-conflict
      - id: check-case-conflict

  # JavaScript/TypeScript linting
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.16.0
    hooks:
      - id: eslint
        files: \.(js|jsx|ts|tsx)$
        exclude: ^(node_modules/|vendor/|web/core/|dist/)
        additional_dependencies:
          - eslint@9.16.0
          - '@typescript-eslint/eslint-plugin@8.18.0'
          - '@typescript-eslint/parser@8.18.0'

  # Markdown linting
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.43.0
    hooks:
      - id: markdownlint
        args: ['--fix']
        exclude: ^(docs/archive/|CHANGELOG\.md)

# Configuration
default_language_version:
  python: python3.12
  node: '22.0.0'

fail_fast: false
