# Gitleaks Configuration für menschlichkeit-oesterreich-development
# Filtere False Positives aus Vendor-Code und Test-Fixtures

title = "Gitleaks Config - Menschlichkeit Österreich"

[extend]
useDefault = true

[[rules]]
id = "generic-api-key"
description = "Generic API Key - DISABLED for vendor/test code"
regex = '''(?i)(api[_-]?key|token|secret).{0,20}[=:]\s*['"]?[a-zA-Z0-9_\-]{16,}['"]?'''
tags = ["key", "API"]
# Disable for vendor paths - use allowlist instead
[rules.allowlist]
paths = [
    # Python virtual environments
    '''api\.menschlichkeit-oesterreich\.at/(\.)?venv/.*''',
    # CRM Vendor Code
    '''crm\.menschlichkeit-oesterreich\.at/web/(core|modules/contrib|vendor)/.*''',
    '''crm\.menschlichkeit-oesterreich\.at/vendor/.*''',
    # Node/Bower dependencies
    '''.*/node_modules/.*''',
    '''.*/bower_components/.*''',
    # Test files and test data
    '''.*/tests?/.*''',
    '''.*[Tt]est\.php$''',
    '''.*_test\.(py|js|ts)$''',
    '''tests/test_pii_sanitizer\.py''',
    # Build artifacts
    '''.*\.pyc$''',
    '''.*/__pycache__/.*''',
    # Development templates and examples
    '''secrets/development/.*''',
    '''secrets/production/.*\.example\.yaml$''',
    '''secrets/production/api-keys\.yaml$''',
    '''config-templates/.*''',
    # Documentation with example secrets
    '''.*\.md$''',
    '''\.github/copilot-instructions\.md''',
    '''PRODUCTION-.*\.md$''',
    '''quality-reports/.*\.md$''',
    '''figma-design-system/.*\.txt$''',
    '''ZUGANGSDATEN-.*\.txt$''',
    '''Website/src/.*\.md$''',
    # PowerShell example scripts
    '''scripts/.*\.ps1$''',
    # Python secret generation scripts (contain templates)
    '''scripts/generate-production-secrets\.py''',
    # VS Code settings (only contains env references)
    '''\.vscode/settings\.json''',
    # GitHub Actions test env
    '''\.github/workflows/api-tests\.yml''',
    # Architecture documentation
    '''Website/src/.*\.md$''',
    '''automation/elk-stack/docker-compose\.yml'''
]

[[rules]]
id = "private-key"
description = "Private Key Detection - DISABLED for test fixtures and docs"
regex = '''-----BEGIN[ A-Z]*PRIVATE KEY-----'''
tags = ["key", "private"]
[rules.allowlist]
paths = [
    '''api\.menschlichkeit-oesterreich\.at/(\.)?venv/.*''',
    '''.*/tests?/.*''',
    '''.*/bower_components/.*''',
    # Legacy prompts and documentation with example keys
    '''\.github/prompts/.*''',
    '''docs/.*\.md$''',
    '''quality-reports/.*\.md$'''
]
regexes = [
    '''REDACTED''',  # Redacted/placeholder keys
    '''SSH_PRIVATE_KEY.*REDACTED'''
]

[[rules]]
id = "aws-access-token"
description = "AWS Access Key - DISABLED for documentation examples"
regex = '''AKIA[0-9A-Z]{16}'''
tags = ["AWS", "key"]
[rules.allowlist]
paths = [
    '''quality-reports/.*\.md$''',
    '''docs/.*\.md$'''
]
regexes = [
    '''AKIAIOSFODNN7EXAMPLE''',  # AWS documentation example
    '''AKIA.*EXAMPLE'''
]

[[rules]]
id = "hashicorp-tf-password"
description = "HashiCorp Terraform Password - DISABLED for PowerShell migration scripts"
regex = '''\bPassword\s*=\s*"[^"]*"'''
tags = ["password", "terraform"]
[rules.allowlist]
paths = [
    '''scripts/wordpress-migration\.ps1$''',
    '''scripts/.*\.ps1$'''
]
regexes = [
    '''SECURE_LARAVEL_2025''',  # Migration script placeholder
    '''SECURE_CIVICRM_2025'''   # Migration script placeholder
]

[allowlist]
description = "Global allowlist for vendor and test code"
paths = [
    '''api\.menschlichkeit-oesterreich\.at/(\.)?venv/.*''',
    '''crm\.menschlichkeit-oesterreich\.at/web/(core|modules/contrib|vendor)/.*''',
    '''.*/node_modules/.*''',
    '''.*/bower_components/.*''',
    '''.*/tests?/.*''',
    '''secrets/development/.*''',
    # Python dependency caches (uv, pip, poetry)
    '''\.ai-sandbox/\.cache/.*''',
    '''\.cache/.*''',
    '''__pycache__/.*''',
    # VS Code backups and caches
    '''\.vscode/mcp-backup-.*\.json$''',
    '''\.vscode/.*-cache/.*''',
    # Environment files (should be in .gitignore anyway)
    '''\.env$''',
    '''\.env\..*''',
    # Example/template files with placeholders
    '''\.env\.example$''',
    '''\.env\.sample$''',
    # Documentation with example keys and placeholders - EXPANDED
    '''GITHUB-SECRETS.*\.md$''',
    '''docs/.*\.md$''',
    '''README\.md$''',
    '''.*README\.md$''',
    '''\.github/prompts/.*\.md$''',
    '''automation/.*/.*\.md$''',
    '''deployment-scripts/.*\.md$''',
    '''quality-reports/.*\.md$''',
    # Secrets template files with REDACTED placeholders
    '''secrets.*\.json$''',
    # VS Code MCP config (local development)
    '''\.vscode/mcp\.json$''',
    '''mcp\.json$''',
    # Chatmode and instruction files with API examples
    '''\.github/chatmodes/.*\.chatmode\.md$''',
    '''\.github/instructions/.*\.instructions\.md$''',
    # MCP Server test and source files
    '''mcp-servers/.*/.*\.(js|ts)$''',
    '''mcp-servers/policies/.*\.(rego|json)$''',
    '''packages/.*/.*\.(js|ts)$''',
    # Security scripts with example commands
    '''scripts/security/.*\.(sh|ps1)$''',
    '''scripts/setup-.*\.(sh|ps1)$'''
]
regexes = [
    '''REPLACE_WITH_.*''',  # Template placeholders
    '''LEGACY_PASSWORD''',  # Legacy placeholder
    '''dev_password_.*''',  # Dev environment
    '''test_password_.*''',  # Test environment
    '''YOUR_.*_HERE''',     # Placeholder pattern
    '''EXAMPLE_.*''',       # Example values
    '''sk_test_.*''',       # Stripe test keys (not production)
    '''YOUR_TOKEN''',       # Generic placeholder in docs
    '''REDACTED''',         # Redacted examples in documentation
    '''Bearer YOUR_.*''',   # Bearer token examples
    '''access_token.*REDACTED''', # API examples with redacted tokens
    '''ghp_1234567890.*''', # Test GitHub PATs with obvious fake pattern
    '''test_key_.*'''       # Test keys
]
