# Logstash Main Configuration
# Project: F-03 Phase 4 - Centralized Log Aggregation
# Purpose: Global Logstash settings

http.host: '0.0.0.0'
http.port: 9600

# Pipeline Configuration
pipeline.workers: 4
pipeline.batch.size: 1000
pipeline.batch.delay: 50

# Queue Configuration
queue.type: persisted
queue.max_bytes: 1gb

# Monitoring
xpack.monitoring.enabled: true
xpack.monitoring.elasticsearch.hosts: ['http://elasticsearch:9200']
xpack.monitoring.elasticsearch.username: 'elastic'
xpack.monitoring.elasticsearch.password: '${ELASTICSEARCH_PASSWORD}'

# Dead Letter Queue
dead_letter_queue.enable: true
dead_letter_queue.max_bytes: 1gb

# Logging
log.level: info
path.logs: /usr/share/logstash/logs
