id: accessibility-audit
version: "0.1.0"
status: deprecated
summary: A11y-Audit nach WCAG 2.2 AA für Web/App-Oberflächen.
purpose: |
  Prüft Barrierefreiheit (Kontrast, Fokus, ARIA, Tastaturbedienung, Alternativtexte)
  und liefert priorisierte Maßnahmen.
triggers:
  - A11y Audit
  - WCAG Review
inputs:
  - name: pages
    description: Liste von Seiten/Ansichten (URLs/Routes)
  - name: scope
    description: App/Website/Komponente
outputs:
  - name: findings
    description: Liste von A11y-Funden mit Schweregrad
  - name: remediation
    description: Konkrete Fixes mit Beispielen
style: |
  WCAG-referenziert (Kriterium, Beleg, Fix). Kurze Sätze, Snippets für ARIA und Semantik.
  Beachte global/01_style_guide.md.
guardrails:
  - Keine PII in Screenshots/Beispielen
  - Beachte global/02_guardrails.md
tools:
  - filesystem
examples:
  positive:
    - Markiert fehlende Fokus-Reihenfolge und bietet Tastatur-Fix
  negative:
    - Allgemeine Hinweise ohne konkreten Fix
tests:
  - assertion: id ist kebab_case
    expected: 'regex:^[a-z0-9]+(-[a-z0-9]+)*$'
  - assertion: Version folgt SemVer
    expected: 'regex:^\d+\.\d+\.\d+$'

