---
status: DEPRECATED
deprecated_date: 2025-10-08
migration_target: .github/chatmodes/Bug_Report_DE.chatmode.md
reason: YAML-Format deprecated - ersetzt durch strukturierte .chatmode.md Dateien
---

**⚠️ DEPRECATED - NICHT VERWENDEN**

Diese Datei ist veraltet und wird in einer zukünftigen Version entfernt.

- **Status:** DEPRECATED
- **Datum:** 2025-10-08
- **Migration:** .github/chatmodes/Bug_Report_DE.chatmode.md
- **Grund:** YAML-Format deprecated - ersetzt durch strukturierte .chatmode.md Dateien

**Aktuelle Version verwenden:** .github/chatmodes/Bug_Report_DE.chatmode.md

---

id: bug-report
version: 0.1.0
status: beta
summary: "Fehlerbericht-Vorlage generieren/prüfen (Reproduktion, Erwartung, Logs, Scope)."
purpose: |
  Hilft beim Erstellen qualitativ hochwertiger Bug-Reports mit Repro-Schritten, Erwartung/Ist,
  Logs/Screenshots und minimalem Scope.
triggers:
  - "Fehlerbericht"
  - "Bug Report"
inputs:
  - name: environment
    description: Umgebung (local/staging/production)
  - name: repro_steps
    description: Reproduktionsschritte
outputs:
  - name: bug_template
    description: Ausgefüllte Vorlage mit klaren Feldern
  - name: triage_notes
    description: Dringlichkeit/Scope/Owner-Empfehlung
style: |
  Präzise, nummerierte Schritte, Logs in Codeblöcken. Screenshots anonymisiert.
guardrails:
  - "Keine Secrets/PII in Logs/Screenshots"
  - "Folge `global/02_guardrails.md`"
tools:
  - filesystem
examples:
  positive:
    - "Nummerierte Repro-Schritte + erwartetes vs. tatsächliches Verhalten"
  negative:
    - "Unspezifische Beschreibung ‚geht nicht‘ ohne Kontext"
tests:
  - assertion: "id ist kebab_case"
    expected: "regex:^[a-z0-9]+(-[a-z0-9]+)*$"
  - assertion: "Version folgt SemVer"
    expected: "regex:^\\d+\\.\\d+\\.\\d+$"

