# Production Environment Database Configuration  
# WARNING: This file contains PRODUCTION secrets and must be encrypted with SOPS
# Encrypt with: sops -e -i secrets/production/database.yaml

database:
  primary:
    host: "db.menschlichkeit-oesterreich.at"
    port: 5432
    name: "menschlichkeit_prod"
    username: "prod_user"
    password: "REPLACE_WITH_STRONG_PRODUCTION_PASSWORD"
    ssl_mode: "require"
    ssl_cert: "/etc/ssl/certs/postgresql-client.crt"
    ssl_key: "/etc/ssl/private/postgresql-client.key"
    ssl_ca: "/etc/ssl/certs/ca-certificates.crt"
    
  readonly:
    host: "db-readonly.menschlichkeit-oesterreich.at"
    port: 5432
    name: "menschlichkeit_prod"
    username: "readonly_user" 
    password: "REPLACE_WITH_READONLY_PASSWORD"
    ssl_mode: "require"
    
  backup:
    host: "db-backup.menschlichkeit-oesterreich.at"
    port: 5432
    name: "menschlichkeit_backup"
    username: "backup_user"
    password: "REPLACE_WITH_BACKUP_PASSWORD"
    ssl_mode: "require"

redis:
  host: "redis.menschlichkeit-oesterreich.at"
  port: 6379
  password: "REPLACE_WITH_REDIS_PASSWORD"
  database: 0
  ssl: true
  
redis_cache:
  host: "cache.menschlichkeit-oesterreich.at"
  port: 6379
  password: "REPLACE_WITH_CACHE_PASSWORD"
  database: 1
  ssl: true