name: API Privacy Tests

on:
  workflow_dispatch:
  push:
    paths:
      - 'api.menschlichkeit-oesterreich.at/**'
      - 'tests/**'
      - '.github/workflows/api-tests.yml'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r api.menschlichkeit-oesterreich.at/app/requirements.txt
      - name: Run tests
        env:
          APP_ENV: development
          CIVI_SITE_KEY: dummy
          CIVI_API_KEY: dummy
          JWT_SECRET: unit_test_secret
        run: |
          pytest -q tests
