name: Codacy analyze edited files

on:
  push:
    paths:
      - "docs/CODEX-EDITOR-USAGE.md"
      - "scripts/check-openai-config.ps1"
  pull_request:
    paths:
      - "docs/CODEX-EDITOR-USAGE.md"
      - "scripts/check-openai-config.ps1"

jobs:
  codacy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      # Erforderlich: in den Repo-Settings als Secret anlegen
      CODACY_TOKEN: ${{ secrets.CODACY_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Fail fast, wenn das Secret fehlt (verhindert irreführende Läufe)
      - name: Verify CODACY_TOKEN is set
        run: |
          if [ -z "${CODACY_TOKEN:-}" ]; then
            echo "ERROR: Repository secret CODACY_TOKEN ist nicht gesetzt."
            echo "Bitte unter Settings → Secrets and variables → Actions anlegen."
            exit 1
          fi

      # Codacy CLI v2 installieren
      - name: Install Codacy CLI v2
        shell: bash
        run: |
          set -euo pipefail
          bash <(curl -Ls https://raw.githubusercontent.com/codacy/codacy-cli-v2/main/codacy-cli.sh)
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"

      # Diagnose & Ausgabe des tatsächlich installierten Pfades
      - name: Locate codacy-cli
        shell: bash
        id: codacy
        run: |
          set -euo pipefail
          which codacy-cli || true
          ls -la "$HOME/.local/bin" || true
          BIN="$(command -v codacy-cli || echo "$HOME/.local/bin/codacy-cli")"
          echo "bin=$BIN" >> "$GITHUB_OUTPUT"
          test -x "$BIN" || (echo "codacy-cli nicht gefunden/ausführbar." && exit 127)

      - name: Codacy CLI version (debug)
        run: ${{ steps.codacy.outputs.bin }} --version

      # Analyse der gezielten Dateien
      - name: Analyze docs/CODEX-EDITOR-USAGE.md
        run: ${{ steps.codacy.outputs.bin }} analyze --rootPath "${GITHUB_WORKSPACE}" --file "docs/CODEX-EDITOR-USAGE.md"

      - name: Analyze scripts/check-openai-config.ps1
        run: ${{ steps.codacy.outputs.bin }} analyze --rootPath "${GITHUB_WORKSPACE}" --file "scripts/check-openai-config.ps1"
