name: Codacy Analyze (optional)
on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Guard — CODACY_TOKEN prüfen
        id: guard
        run: |
          if [[ -z "${{ secrets.CODACY_TOKEN }}" ]]; then
            echo "has_token=false" >> "$GITHUB_OUTPUT"
            echo "CODACY_TOKEN nicht gesetzt — Codacy-Analyse wird übersprungen."
          else
            echo "has_token=true" >> "$GITHUB_OUTPUT"
            echo "CODACY_TOKEN vorhanden — Codacy-Analyse wird ausgeführt."
          fi

      - name: Skip — kein Token vorhanden
        if: steps.guard.outputs.has_token != 'true'
        run: echo "CODACY_TOKEN nicht gesetzt — Workflow übersprungen."

      - name: Codacy Analysis
        if: steps.guard.outputs.has_token == 'true'
        uses: codacy/codacy-analysis-cli-action@v4
        with:
          api-token: ${{ secrets.CODACY_TOKEN }}
          tool: eslint
          directory: .
          format: sarif
          output: codacy.sarif

      - name: Codacy Zusammenfassung
        if: steps.guard.outputs.has_token == 'true'
        run: |
          if [[ -f codacy.sarif ]]; then
            echo "Codacy SARIF erzeugt: $(wc -c < codacy.sarif) bytes"
          else
            echo "Keine SARIF-Datei von Codacy erzeugt."
          fi
