name: Codacy analyze edited files

on:
  push:
    paths:
      - "docs/CODEX-EDITOR-USAGE.md"
      - "scripts/check-openai-config.ps1"
  pull_request:
    paths:
      - "docs/CODEX-EDITOR-USAGE.md"
      - "scripts/check-openai-config.ps1"

jobs:
  codacy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      # Erforderlich: in den Repo-Settings als Secret anlegen
      CODACY_TOKEN: ${{ secrets.CODACY_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Variante A: Offizielles CLI v2 per Installer-Skript
      - name: Install Codacy CLI v2
        run: |
          set -e
          bash <(curl -Ls https://raw.githubusercontent.com/codacy/codacy-cli-v2/main/codacy-cli.sh)
          echo "$HOME/.local/bin" >> $GITHUB_PATH || true
          ls -la $HOME/.local/bin || true

      - name: Prepare codacy-cli binary
        run: |
          if command -v codacy-cli >/dev/null 2>&1; then
            echo "codacy-cli in PATH"
            which codacy-cli
          elif [ -x "$HOME/.local/bin/codacy-cli" ]; then
            echo "codacy-cli installed to $HOME/.local/bin"
            export PATH="$HOME/.local/bin:$PATH"
            which codacy-cli || true
          else
            echo "codacy-cli not found after install" >&2
            ls -la $HOME/.local || true
            exit 2
          fi

      - name: Verify CODACY_TOKEN
        run: |
          if [ -z "${CODACY_TOKEN}" ]; then
            echo "ERROR: CODACY_TOKEN is empty. Set repository secret 'CODACY_TOKEN' in Settings -> Secrets and variables -> Actions." >&2
            exit 3
          fi

      - name: Codacy CLI version (debug)
        run: codacy-cli --version || $HOME/.local/bin/codacy-cli --version || true

      - name: Analyze docs/CODEX-EDITOR-USAGE.md
        run: codacy-cli analyze --rootPath "${GITHUB_WORKSPACE}" --file "docs/CODEX-EDITOR-USAGE.md" || $HOME/.local/bin/codacy-cli analyze --rootPath "${GITHUB_WORKSPACE}" --file "docs/CODEX-EDITOR-US.md"

      - name: Analyze scripts/check-openai-config.ps1
        run: codacy-cli analyze --rootPath "${GITHUB_WORKSPACE}" --file "scripts/check-openai-config.ps1" || $HOME/.local/bin/codacy-cli analyze --rootPath "${GITHUB_WORKSPACE}" --file "scripts/check-openai-config.ps1"
