name: DB Pull (Plesk → Artifact)

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment (z. B. stage|prod)"
        required: true
        default: "prod"

permissions:
  contents: read

jobs:
  dump:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      SSH_HOST: ${{ secrets.PLESK_HOST }}
      SSH_PORT: ${{ secrets.PLESK_SSH_PORT || '22' }}
      SSH_USER: ${{ secrets.PLESK_USER }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASS: ${{ secrets.DB_PASS }}
    steps:
      - name: Start ssh-agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.PLESK_SSH_KEY }}

      - name: Trust host key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p "${{ env.SSH_PORT }}" -H "${{ env.SSH_HOST }}" >> ~/.ssh/known_hosts

      - name: Stream mysqldump → gzip
        run: |
          TS=$(date -u +'%Y%m%d-%H%M%S')
          OUT="db-${{ inputs.environment }}-${TS}.sql.gz"
          ssh -p "${{ env.SSH_PORT }}" "${{ env.SSH_USER }}@${{ env.SSH_HOST }}" \
            "MYSQL_PWD='${{ env.DB_PASS }}' mysqldump -h '${{ env.DB_HOST }}' -u '${{ env.DB_USER }}' --single-transaction --quick --routines --triggers --events '${{ env.DB_NAME }}' | gzip -c" \
            > "$OUT"
          echo "OUT=$OUT" >> $GITHUB_ENV

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.OUT }}
          path: ${{ env.OUT }}
          retention-days: 5
