name: Gitleaks

on:
  push:
    branches: [ main, master, chore/**, feature/** ]
  pull_request:
    branches: [ main, master, chore/**, feature/** ]

permissions:
  contents: read

jobs:
  Gitleaks:
    name: Gitleaks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: --no-git --source . --config .gitleaks.toml --redact

