name: Trivy FS Scan

on:
  push:
    branches: [ main, master, chore/**, feature/** ]
  pull_request:
    branches: [ main, master, chore/**, feature/** ]

permissions:
  contents: read

jobs:
  trivy:
    name: Trivy FS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Trivy filesystem scan
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: 'fs'
          format: 'sarif'
          output: 'trivy-fs.sarif'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-fs.sarif

