name: Trivy FS Scan

on:
  push:
    branches: [ main, master, chore/**, feature/** ]
  pull_request:
    branches: [ main, master, chore/**, feature/** ]

permissions:
  contents: read

jobs:
  trivy:
    name: Trivy FS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # ref: v4
        with:
          fetch-depth: 0

      - name: Run Trivy filesystem scan (non-blocking)
        uses: aquasecurity/trivy-action@6e7b7d1fd3e4fef0c5fa8cce1229c54b2c9bd0d8 # ref: 0.24.0
        with:
          scan-type: 'fs'
          format: 'sarif'
          output: 'trivy-fs.sarif'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
        continue-on-error: true

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-fs.sarif
